import type { CollectionConfig } from 'payload'

export const CollectionOperations: CollectionConfig = {
  slug: 'collection-operations',
  dbName: 'collection_operations',
  admin: { hidden: true },
  access: { create: () => false, read: () => false, update: () => false, delete: () => false },
  fields: [
    { name: 'collectionId', type: 'text', required: true, index: true },
    { name: 'parentOperationId', type: 'text' },
    { name: 'mode', type: 'select', required: true, options: ['explicit', 'selection'] },
    { name: 'action', type: 'select', required: true, options: ['add', 'remove'] },
    { name: 'selectionId', type: 'text' },
    { name: 'operationSequence', type: 'number', required: true },
    { name: 'baseDraftRevision', type: 'number', required: true },
    { name: 'targetDraftRevision', type: 'number', required: true },
    { name: 'idempotencyKey', type: 'text', required: true },
    { name: 'requestHash', type: 'text', required: true },
    { name: 'selectedCount', type: 'number', required: true },
    {
      name: 'status',
      type: 'select',
      required: true,
      options: [
        'queued',
        'materializing',
        'staging',
        'validating',
        'committing',
        'committed',
        'completed',
        'completed_with_skips',
        'failed',
        'cancelled',
        'stale',
        'conflicted',
        'authorization_revoked',
      ],
      index: true,
    },
    { name: 'progress', type: 'json', required: true },
    { name: 'checkpoint', type: 'text' },
    { name: 'leaseOwner', type: 'text' },
    { name: 'leaseExpiresAt', type: 'date', index: true },
    { name: 'fencingToken', type: 'number', required: true, defaultValue: 0 },
    { name: 'actorId', type: 'text', required: true },
    { name: 'requestId', type: 'text', required: true },
    { name: 'jobId', type: 'text', required: true, index: true },
    { name: 'errorCode', type: 'text' },
  ],
}
