/**
 * Editorial registry for the three record families the Admin renders.
 *
 * The registry describes fields; it never decides which fields exist. Anything
 * a stored record carries but this file does not list still renders — it is
 * simply unlabelled, see `record-inspector.ts`.
 */

import type { ContentRecordKind, FieldDescriptor } from './field-types'

/**
 * Curation documents: the curator's recommendation and its sources.
 *
 * `filterable` marks the paths the catalog clause boundary evaluates, so the
 * advanced field search (plan §8) can offer exactly those. The open-ended
 * `categories.<Category>` and `sources.<key>` shapes are covered by their root
 * entries and are surfaced as templates by the filter builder.
 */
export const CURATION_FIELDS = [
  {
    path: 'curation_id',
    label: 'Curation id',
    owner: 'system',
    type: 'text',
    system: true,
    section: 'Identity',
  },
  {
    path: 'entity_id',
    label: 'Entity',
    owner: 'curation',
    type: 'relationship',
    relationship: { kind: 'entity', edit: 'identifier' },
    editable: true,
    searchable: true,
    filterable: true,
    section: 'About',
  },
  {
    path: 'restaurant_name',
    label: 'Restaurant name',
    owner: 'curation',
    type: 'text',
    editable: true,
    searchable: true,
    filterable: true,
    listable: true,
    section: 'About',
  },
  {
    path: 'status',
    label: 'Status',
    owner: 'curation',
    type: 'enum',
    enumValues: ['draft', 'linked', 'active', 'deleted', 'archived'],
    editable: true,
    filterable: true,
    listable: true,
    section: 'About',
  },
  {
    path: 'curator_id',
    label: 'Curator',
    owner: 'system',
    type: 'text',
    system: true,
    filterable: true,
    section: 'About',
    help: 'Curator reassignment runs through the bulk action; there is no user directory endpoint yet.',
  },
  {
    path: 'curator.name',
    label: 'Curator',
    owner: 'curation',
    type: 'text',
    editable: false,
    derivedIn: 'curation',
    derivedFrom: 'Curator',
    filterable: true,
    section: 'About',
  },
  {
    path: 'curator.email',
    label: 'Curator email',
    owner: 'curation',
    type: 'text',
    editable: false,
    system: true,
    section: 'About',
  },
  {
    path: 'curator_type',
    label: 'Curator type',
    owner: 'curation',
    type: 'enum',
    enumValues: ['human', 'synthetic'],
    editable: true,
    filterable: true,
    section: 'About',
  },
  {
    path: 'notes.public',
    label: 'Public recommendation',
    owner: 'curation',
    type: 'longText',
    editable: true,
    searchable: true,
    filterable: true,
    section: 'Your curation',
  },
  {
    path: 'notes.private',
    label: 'Private note',
    owner: 'curation',
    type: 'longText',
    editable: true,
    searchable: true,
    filterable: true,
    section: 'Your curation',
  },
  {
    path: 'city',
    label: 'City',
    owner: 'entity',
    type: 'text',
    editable: false,
    derivedIn: 'curation',
    derivedFrom: 'Entity',
    filterable: true,
    listable: true,
    section: 'About',
  },
  {
    path: 'type',
    label: 'Type',
    owner: 'entity',
    type: 'text',
    editable: false,
    derivedIn: 'curation',
    derivedFrom: 'Entity',
    filterable: true,
    listable: true,
    section: 'About',
  },
  {
    path: 'categories',
    label: 'Concepts',
    owner: 'curation',
    type: 'concept',
    editable: true,
    searchable: true,
    filterable: true,
    section: 'Concepts',
  },
  {
    path: 'transcript',
    label: 'Transcript',
    owner: 'curation',
    type: 'longText',
    editable: true,
    searchable: true,
    filterable: true,
    section: 'Media & sources',
  },
  {
    path: 'sources',
    label: 'Sources',
    owner: 'curation',
    type: 'object',
    editable: true,
    filterable: true,
    section: 'Media & sources',
  },
  {
    path: 'items',
    label: 'Items',
    owner: 'curation',
    type: 'array',
    editable: true,
    section: 'Your curation',
  },
  {
    path: 'embeddings',
    label: 'Embeddings',
    owner: 'system',
    type: 'binary',
    system: true,
    section: 'Advanced',
    help: 'Stored inline as Binary float32; the API returns its shape, never the raw bytes.',
  },
  {
    path: 'embeddings_metadata',
    label: 'Embeddings metadata',
    owner: 'system',
    type: 'object',
    system: true,
    section: 'Advanced',
  },
  {
    path: 'createdBy',
    label: 'Created by',
    owner: 'system',
    type: 'text',
    system: true,
    section: 'History',
  },
  {
    path: 'updatedBy',
    label: 'Updated by',
    owner: 'system',
    type: 'text',
    system: true,
    section: 'History',
  },
  {
    path: 'createdAt',
    label: 'Created',
    owner: 'system',
    type: 'dateTime',
    system: true,
    filterable: true,
    section: 'History',
  },
  {
    path: 'updatedAt',
    label: 'Updated',
    owner: 'system',
    type: 'dateTime',
    system: true,
    listable: true,
    filterable: true,
    section: 'History',
  },
  {
    path: 'version',
    label: 'Version',
    owner: 'system',
    type: 'number',
    system: true,
    filterable: true,
    section: 'History',
  },
  {
    path: 'catalog_sequence',
    label: 'Catalog sequence',
    owner: 'system',
    type: 'number',
    system: true,
    filterable: true,
    section: 'Advanced',
  },
] satisfies readonly FieldDescriptor[]

/** Canonical entities: restaurants, hotels and the like. */
export const ENTITY_FIELDS = [
  {
    path: 'entity_id',
    label: 'Entity id',
    owner: 'system',
    type: 'text',
    system: true,
    section: 'Identity',
  },
  {
    path: 'name',
    label: 'Name',
    owner: 'entity',
    type: 'text',
    editable: true,
    searchable: true,
    listable: true,
    section: 'Canonical identity',
  },
  {
    path: 'type',
    label: 'Type',
    owner: 'entity',
    type: 'enum',
    enumValues: ['restaurant', 'hotel', 'venue', 'bar', 'cafe', 'other'],
    editable: true,
    searchable: true,
    listable: true,
    section: 'Canonical identity',
  },
  {
    path: 'status',
    label: 'Status',
    owner: 'entity',
    type: 'enum',
    enumValues: ['active', 'inactive', 'draft'],
    editable: true,
    listable: true,
    section: 'Canonical identity',
  },
  {
    path: 'externalId',
    label: 'External id',
    owner: 'entity',
    type: 'text',
    editable: true,
    searchable: true,
    section: 'Identity',
  },
  {
    path: 'metadata',
    label: 'Metadata',
    owner: 'entity',
    type: 'array',
    editable: true,
    section: 'Metadata',
  },
  {
    path: 'sync',
    label: 'Sync',
    owner: 'entity',
    type: 'object',
    editable: true,
    section: 'Metadata',
  },
  {
    path: 'data',
    label: 'Attributes',
    owner: 'entity',
    type: 'object',
    editable: true,
    searchable: true,
    section: 'Attributes',
  },
  {
    path: 'createdBy',
    label: 'Created by',
    owner: 'system',
    type: 'text',
    system: true,
    section: 'History',
  },
  {
    path: 'updatedBy',
    label: 'Updated by',
    owner: 'system',
    type: 'text',
    system: true,
    section: 'History',
  },
  {
    path: 'createdAt',
    label: 'Created',
    owner: 'system',
    type: 'dateTime',
    system: true,
    section: 'History',
  },
  {
    path: 'updatedAt',
    label: 'Updated',
    owner: 'system',
    type: 'dateTime',
    system: true,
    section: 'History',
  },
  {
    path: 'version',
    label: 'Version',
    owner: 'system',
    type: 'number',
    system: true,
    section: 'History',
  },
] satisfies readonly FieldDescriptor[]

/** Payload-side Collection records: the published editorial groupings. */
export const COLLECTION_FIELDS = [
  {
    path: 'title',
    label: 'Title',
    owner: 'collection',
    type: 'text',
    editable: true,
    searchable: true,
    listable: true,
  },
  {
    path: 'slug',
    label: 'Slug',
    owner: 'collection',
    type: 'text',
    editable: true,
    searchable: true,
    listable: true,
  },
  {
    path: 'description',
    label: 'Description',
    owner: 'collection',
    type: 'longText',
    editable: true,
    searchable: true,
  },
  {
    path: 'lifecycle',
    label: 'Lifecycle',
    owner: 'collection',
    type: 'enum',
    enumValues: ['draft', 'published', 'archived'],
    editable: false,
    listable: true,
  },
  {
    path: 'currentPublishedVersion',
    label: 'Published version',
    owner: 'collection',
    type: 'number',
    system: true,
  },
  {
    path: 'draftRevision',
    label: 'Draft revision',
    owner: 'collection',
    type: 'number',
    system: true,
  },
  {
    path: 'draftState',
    label: 'Draft state',
    owner: 'collection',
    type: 'enum',
    enumValues: ['clean', 'dirty'],
    editable: false,
  },
  {
    path: 'publishedSelectedCount',
    label: 'Published members',
    owner: 'collection',
    type: 'number',
    system: true,
  },
  {
    path: 'draftSelectedCount',
    label: 'Draft members',
    owner: 'collection',
    type: 'number',
    system: true,
  },
  {
    path: 'revision',
    label: 'Revision',
    owner: 'collection',
    type: 'number',
    system: true,
  },
  {
    path: 'createdAt',
    label: 'Created',
    owner: 'system',
    type: 'dateTime',
    system: true,
  },
  {
    path: 'updatedAt',
    label: 'Updated',
    owner: 'system',
    type: 'dateTime',
    system: true,
  },
] satisfies readonly FieldDescriptor[]

const REGISTRY: Record<ContentRecordKind, readonly FieldDescriptor[]> = {
  curation: CURATION_FIELDS,
  entity: ENTITY_FIELDS,
  collection: COLLECTION_FIELDS,
}

/** The descriptors of one record family, in registry order. */
export function descriptorsFor(kind: ContentRecordKind): readonly FieldDescriptor[] {
  return REGISTRY[kind]
}
